# Generated by Django 3.2.6 on 2021-08-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_price_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
