# Generated by Django 3.2.6 on 2021-12-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.TextField(default=123, max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
